### ISSUE TITLE
 sci-geosciences/google-earth-bin-7.3.4 version bump

### ISSUE THREAD

**Issue by JAKuhr** [BlueManCZ/edgets#12]
Google seems to have updated google earth without a version bump:

!!! Fetched file: google-earth-bin-7.3.4.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      55949724
!!! Expected: 55716868

Perhaps you could update the ebuild. Yours was the last one that worked for me. Thank you!

**Comment by BlueManCZ** [comment]
Hello, thank you for letting me know. They do this quite often. :man_shrugging: It should be fixed now.

**Comment by JAKuhr** [comment]
Thank you. The download issue is fixed now.

Unfortunately Google Earth crashes for me on start: "Google Earth has caught signal 6." 

Does it work for you?

**Comment by BlueManCZ** [comment]
Strange. Does it generate some crashlog?

Yes, it works fine for me.

<img src="https://user-images.githubusercontent.com/17854950/166460844-c007ab37-ea22-4154-a2dd-45382bca7ba7.png" width="250px">

If you manage to find what is causing you troubles, let me know, we can try to improve this ebuild. Maybe some missing dependencies?

Got a few hits from the search engine:
https://bbs.archlinux.org/viewtopic.php?id=83095
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215500

It may be related to anything - graphics drivers, audio configuration, desktop environment...

What if you download [.deb](https://dl.google.com/dl/linux/direct/google-earth-pro-stable_7.3.4_amd64.deb) file directly, extract it and then execute it from there? Does it start?

**Comment by JAKuhr** [comment]
After todays xorg/mesa/wayland update it works for me. Probably it was some kind of graphics driver related problem. Thank you!

**Comment by BlueManCZ** [comment]
Great! Since the google-earth is provided only as a binary, it is possible it was compiled with newer versions of graphics libraries and those were not in Gentoo until now.
