### ISSUE TITLE
dev-java/liberica-jre-bin improvements and issues

### ISSUE THREAD

**Issue by jonasstein** [BlueManCZ/edgets#13]
I had a short look on https://github.com/gentoo-mirror/edgets/blob/master/dev-java/liberica-jre-bin/liberica-jre-bin-17_p35.ebuild
because of https://bugs.gentoo.org/875878

```
LICENSE="GPL-2"
RESTRICT="mirror"

```
makes no sense to me is the LICENSE wrong?

`mv` misses a `die`

**Comment by BlueManCZ** [comment]
Hello, liberica-jre-bin is licenced under The GNU General Public License Version 2. You can check the LICENCE file that is included in the [bellsoft-jre13.0.1-linux-amd64.tar.gz](https://download.bell-sw.com/java/13.0.1/bellsoft-jre13.0.1-linux-amd64.tar.gz) archive. If you are implying that `RESTRICT="mirror"` doesn't make sense in this context, you may be right. I use this restriction in the majority of my overlay ebuilds but only as a signal for portage to not look for the distfiles in official Gentoo mirrors and instead download them directly from provided URI.

I added `die` after the `mv`.
