### ISSUE TITLE
sci-geosciences/google-earth-bin-7.3.4 version bump

### ISSUE THREAD

**Issue by JAKuhr** [BlueManCZ/edgets#14]
Google seems to have updated google earth again without a version bump:

!!! Fetched file: google-earth-bin-7.3.4.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      55955782
!!! Expected: 55949724

Perhaps you could update the ebuild. Thank you very much!

**Comment by BlueManCZ** [comment]
Hi, sure thing! Thank you for letting me know.

**Comment by JAKuhr** [comment]
Works fine now! Thank you very much!
