### ISSUE TITLE
simplenote depends on removed gconf

### ISSUE THREAD

**Issue by APN-Pucky** [BlueManCZ/edgets#16]
```
!!! The following update has been skipped due to unsatisfied dependencies:

app-text/simplenote-bin:0

  selected: (app-text/simplenote-bin-2.20.0:0/0::edgets, ebuild scheduled for merge)
  skipped: (app-text/simplenote-bin-2.21.0:0/0::edgets, ebuild scheduled for merge) (see unsatisfied dependency below)

emerge: there are no ebuilds to satisfy "gnome-base/gconf:2".
(dependency required by "app-text/simplenote-bin-2.21.0::edgets" [ebuild])
```

Masked and removed here: 
https://bugs.gentoo.org/873841
https://github.com/gentoo/gentoo/commit/963a3cbba2be70654ff43094f7e696d56dd5c33e

**Comment by BlueManCZ** [comment]
Hello, thank you for reporting this. I updated the ebuild and renamed it to `app-text/simplenote`. Don't forget to unmerge the old package first. Let me know how it works for you.

**Comment by APN-Pucky** [comment]
Thanks. All seems to work well.
