### ISSUE TITLE
sci-geosciences/google-earth-bin-7.3.3 download problem

### ISSUE THREAD

**Issue by ghost** [BlueManCZ/edgets#3]
!!! Fetched file: google-earth-bin-7.3.3.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      56057072
!!! Expected: 56036136
Refetching... File renamed to '/var/cache/distfiles/google-earth-bin-7.3.3.deb._checksum_failure_.6ifml1yk'

got Filesize does not match recorded size

**Comment by BlueManCZ** [comment]
Thank you for the notification! They updated the file without bumping version for some reason. Should be [fixed](https://github.com/BlueManCZ/edgets/commit/ae0d8506b25ef496789148ba10b2c2bdca8f4a75) now.
