### ISSUE TITLE
Add cura and dependencies to repository

### ISSUE THREAD

**Issue by hrnick** [BlueManCZ/edgets#5]
Hi!

I've bumped the version to 4.9.1 and slightly modified the cura ebuild found in the official gentoo repository according to the list below. I'd be happy if these files could be made available for everyone through edgets and not just lie around on my computer. :)

Bumped ebuild and patches from 4.8.0
dev-python/pynest2d/pynest2d-4.9.1.ebuild
dev-python/pynest2d/files/pynest2d-4.9.1-fix-cpp-version.patch
dev-python/pynest2d/files/pynest2d-4.9.1-required-flags-from-Libnest2D-target.patch

Bumped ebuild from 4.8.0
dev-python/uranium/uranium-4.9.1.ebuild

Bumped ebuild and patches from 4.8.0
dev-libs/libarcus/files/libarcus-4.9.1-deprecated-protobuf-calls.patch
dev-libs/libarcus/libarcus-4.9.1.ebuild

Bumped ebuild from 4.8.0
dev-libs/libcharon/libcharon-4.9.1.ebuild

Bumped ebuild and patches from 4.8.0
dev-libs/libsavitar/files/libsavitar-4.9.1-use-system-pugixml.patch
dev-libs/libsavitar/libsavitar-4.9.1.ebuild

Patch from https://src.fedoraproject.org/rpms/cura/blob/2cdec4003addb81fca79344e592cc0b3c5c07f34/f/cura-9702.patch
Added RDEPEND according to https://bugs.gentoo.org/731274
Bumped ebuild from 4.8.0
media-gfx/cura/files/cura-4.9.1-fix_test_wrongServerResponses.patch
media-gfx/cura/cura-4.9.1.ebuild

Bumped ebuild from 4.8.0
media-gfx/curaengine/curaengine-4.9.1.ebuild

Bumped ebuild from 4.8.0
media-gfx/fdm-materials/fdm-materials-4.9.1.ebuild

Thanks!

[cura.tar.gz](https://github.com/BlueManCZ/edgets/files/6593770/cura.tar.gz)

**Comment by hrnick** [comment]
I might have been a little too quick, this emerged fine just a few days ago but now that I tried them I ran into problems. It seems as if dev-python/sip-5.5.0 breaks some packages unable to find sip all of a sudden. There are some bug reports on this already so I would guess that there's something going on with that package. It works fine with sip-4.19.25.

**Comment by BlueManCZ** [comment]
Alright, let me know if you find a solution to this. Maybe specifying <sip-5.5.0 in dependencies may do the trick for now, since 5.5.0 is still in testing?

**Comment by hrnick** [comment]
Yeah, sorry about that again. I think adding that would make sense at this point. So should I edit and submit or would you add that?

**Comment by BlueManCZ** [comment]
If you can edit and test it if it works it would be great.

**Comment by hrnick** [comment]
I added sip version to libarcus-4.9.1.ebuild:
`<dev-python/sip-5.5.0[${PYTHON_MULTI_USEDEP}]`

I can confirm that it works.

```
$ emerge sip -vp

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-python/sip-4.19.25:0/12::gentoo  USE="-doc" PYTHON_TARGETS="python3_9 -python3_10 -python3_8" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

dev-python/sip:0

  (dev-python/sip-5.5.0:0/12::gentoo, ebuild scheduled for merge) USE="-doc" PYTHON_TARGETS="python3_9 -python3_10 -python3_8" conflicts with
    <dev-python/sip-5.5.0[python_targets_python3_9(-)] required by (dev-libs/libarcus-4.9.1:0/3::localrepo, installed) USE="python -examples -static-libs" PYTHON_SINGLE_TARGET="python3_9 -python3_8"
    ^               ^^^^^                             
```

Thanks!

[libarcus-4.9.1.tar.gz](https://github.com/BlueManCZ/edgets/files/6594000/libarcus-4.9.1.tar.gz)

**Comment by BlueManCZ** [comment]
So, now everything should be public. :clinking_glasses: Ebuilds seems to be working just fine, I tested them all.

If you can double-check everything and maybe test it once more, it would be great.

![Snímek z 2021-06-04 15-21-02](https://user-images.githubusercontent.com/17854950/120807912-c4806c80-c548-11eb-84be-612265b9eae9.png)

**Comment by hrnick** [comment]
Cool! I hope someone finds them useful! I have removed the ebuilds from my local repository and emerged them from edgets and it works fine on my end as well..

Thanks! :)

**Comment by BlueManCZ** [comment]
Great, so I'm going to close this. Feel free to always open a new issue for further ebuilds.
