### ISSUE TITLE
x11-libs/bamf requires gtk-docs even when compiled with -doc

### ISSUE THREAD

**Issue by dcrook** [BlueManCZ/edgets#7]
Hi, I just tried upgrading to the your x11-libs/bamf-0.5.0 ebuild and it looks like the gtk-docs package is required even if you are compiling without the doc use flag set.  The ebuild did work correctly when I manually installed gtk-docs.

**Comment by BlueManCZ** [comment]
Hello, thank you for letting me know! I know I noticed this in the past, but missed it in the latest pull request. It should be fixed now. :penguin:
