### ISSUE TITLE
sci-geosciences/google-earth-bin Add media-libs/gst-plugins-base to RDEPEND

### ISSUE THREAD

**Issue by jeandestouches** [BlueManCZ/edgets#9]
Hi,
Just to let you know that media-libs/gst-plugins-base is necessary to load it correctly. (Otherwise it refuse to start complaining about missing gst libraries) Maybe gstreamer is supposed to pull it automatically but on my system I have masked globally so adding media-libs/gst-plugins-base in addition would be good I think, to make sure it is installed.
Otherwise, it works perfectly ! Thank you for the nice ebuild !
Cheers

**Comment by BlueManCZ** [comment]
Hello, thank you for letting me know! It should be alright now. Have a nice day. :octocat:
